/**
 * Worker bindings and secrets. The `Env` interface itself is generated by
 * `pnpm cf-typegen` (wrangler types) into worker-configuration.d.ts from
 * wrangler.jsonc + .dev.vars.example, so it stays in sync with the config.
 * This module just re-exports it under a friendlier name and documents
 * the secrets that are not in wrangler.jsonc.
 */
export type Bindings = Env & {
  /** Wrangler secret. 32+ random chars. */
  BETTER_AUTH_SECRET: string;
  /** Wrangler secret. Public origin, e.g. https://nestimate.example.workers.dev */
  BETTER_AUTH_URL: string;
  /** Optional Wrangler secrets; GitHub sign-in is hidden unless both are set. */
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
};

export function isSecretConfigured(v: string | undefined): v is string {
  return typeof v === "string" && v.length > 0;
}
